name: HBI NXL Technical CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Setup .NET
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: "8.0.x"

            - name: Restore dependencies
              run: dotnet restore API/API.csproj

            - name: Build
              run: dotnet build API/API.csproj --configuration Release --no-restore

            - name: Test
              run: dotnet test API/API.csproj --no-restore --verbosity normal

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "20.17.0"

            - name: Install and build Angular app
              run: |
                  cd WebApp
                  npm ci
                  npm run build -- --configuration production
